services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/simple-finance
    ports:
      - "3000:3000"
    depends_on:
      - db
    # command: rails server -b 0.0.0.0
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

volumes:
  db-data:
