default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

user: &user
  username: nicolas
  password: 123456

development:
  <<: *default
  <<: *user
  database: simple_finance_master

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL") { '' } %>
  database: simple_finance_production
